/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: src/theme/rog.ts
 * Command: astryx theme build src/theme/rog.ts --out src/theme/built/rog.css
 * CLI: @astryxdesign/cli@0.5.2
 * Core: @astryxdesign/core@0.5.2
 */

/// <reference path="./rog.variants.d.ts" />
import type { DefinedTheme } from '@astryxdesign/core/theme';
export declare const rogTheme: DefinedTheme;
