/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: src/theme/rog.ts
 * Command: astryx theme build src/theme/rog.ts --out src/theme/built/rog.css
 * CLI: @astryxdesign/cli@0.5.2
 * Core: @astryxdesign/core@0.5.2
 */

// Generated by astryx theme build
export {};

declare module '@astryxdesign/core/Badge' {
  interface BadgeVariantMap {
    'gray': true;
  }
}
